name: Branch Name Check

on:
  create:
    branches:
      - '**'

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        if: "!startsWith(github.ref, 'refs/heads/test-star')"
        run: |
          echo "Branch name is invalid. Deleting branch..."
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/git/refs/heads/$BRANCH_NAME
