name: Branch Name Check

on:
  create:
    branches:
      - '**'

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        id: check
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          if [[ "$BRANCH_NAME" != test-star* ]]; then
            echo "Branch name is invalid. Deleting branch..."
            curl -X DELETE -H "Authorization: Bearer ${{ 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 }}" \
            https://api.github.com/repos/${{ github.repository }}/git/refs/heads/$BRANCH_NAME
            echo "::set-output name=is_invalid::true"
          else
            echo "::set-output name=is_invalid::false"

      - name: Fail if invalid
        if: steps.check.outputs.is_invalid == 'true'
        run: exit 1
