name: Branch Name Check

on:
  create:
    branches:
      - '**'

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        id: check
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          if [[ "$BRANCH_NAME" != test-star* ]]; then
            echo "Branch name is invalid. Deleting branch..."
            curl -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/git/refs/heads/$BRANCH_NAME
            echo "is_invalid=true" >> $GITHUB_ENV
          else
            echo "is_invalid=false" >> $GITHUB_ENV

      - name: Fail if invalid
        if: env.is_invalid == 'true'
        run: exit 1
